# Minimal Conductor OSS settings for docker compose.
server.port=8080
# datasource for conductor-postgres
conductor.persistence.type=postgres
conductor.db.jdbc.url=jdbc:postgresql://conductor-postgres:5432/conductor
conductor.db.jdbc.username=conductor
conductor.db.jdbc.password=conductor
# lightweight defaults
